### ISSUE TITLE
Failed to download some lfw-google images. Any negative effects? (CuDnn 7 support?)

### ISSUE THREAD

**Issue by yyyreal** [paulu/deepfeatinterp#13]
About 1000 urls in `lfwgoogle_urls.txt` seems to be lapsed. Is there any negative effects in re-building dataset?

**Comment by paulu** [comment]
Go ahead and rebuild the dataset. The rebuild script will remove the missing files.

**Comment by yyyreal** [comment]
Thanks for your reply.

**Comment by yyyreal** [comment]
But another error occurred. I'm using a V100 with CUDA9.1 and CUDNN7. caffe and torch run perfectly on this machine. But when I run `python dataset_rebuild.py` ,  Errors displayed are as follows:

```
Found 613762 images.
Found 613762 new images.
Loaded 0 descriptors.
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    import facemodel
  File "/data/yuyangyang/open_source_network/deepfeatinterp/models/facemodel/facemodel.py", line 20, in <module>
    require('cudnn')
  File "/usr/local/lib/python2.7/dist-packages/lutorpy/__init__.py", line 112, in require
    ret = luaRuntime.require(module_name)
  File "lutorpy/_lupa.pyx", line 318, in lutorpy._lupa.LuaRuntime.require (lutorpy/_lupa.c:6189)
  File "lutorpy/_lupa.pyx", line 1658, in lutorpy._lupa.call_lua (lutorpy/_lupa.c:25877)
  File "lutorpy/_lupa.pyx", line 1667, in lutorpy._lupa.execute_lua_call (lutorpy/_lupa.c:25987)
  File "lutorpy/_lupa.pyx", line 1620, in lutorpy._lupa.raise_lua_error (lutorpy/_lupa.c:25297)
lutorpy._lupa.LuaError: /home/dockeruser/torch/install/share/lua/5.1/cudnn/ffi.lua:1603: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in
your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

Alternatively, set the path to libcudnn.so.5 or libcudnn.5.dylib
to the environment variable CUDNN_PATH and rerun torch.
For example: export CUDNN_PATH="/usr/local/cuda/lib64/libcudnn.so.5"

Traceback (most recent call last):
  File "dataset_rebuild.py", line 204, in <module>
    rebuild_dataset(interactive=True)
  File "dataset_rebuild.py", line 132, in rebuild_dataset
    scores=facemodel_server_predict(p,ipath)
  File "/data/yuyangyang/open_source_network/deepfeatinterp/facemodel_server.py", line 32, in facemodel_server_predict
    scores=pickle.loads(rawdata.decode('string_escape'))
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 886, in load_eof
    raise EOFError
EOFError
```
How can I adjust codes, since I can not change the dev environment on this server? Much thanks...

**Comment by yyyreal** [comment]
I found this, which could be useful.

`git clone https://github.com/soumith/cudnn.torch.git -b R7 && cd cudnn.torch && luarocks make cudnn-scm-1.rockspec
`

**Comment by paulu** [comment]
It sounds like a problem with lutorpy. I suggest checking your lutorpy install with their tutorials.

**Comment by yyyreal** [comment]
Latest lutorpy was updated about 2 years age before cudnn 7 was launched. The scripts I pasted above solves my issue. Now I am re-building the dataset. (Indeed slow, even on V100)
